### ISSUE TITLE
ERROR: for pyddns_nginx_1  a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by kgnfth** [olimpo88/PyDDNS#17]
i get this error pls hAlp

```
root@ddns:~/PyDDNS# lsof -i -P -n | grep LISTEN
sshd        191            root    3u  IPv4  7340118      0t0  TCP *:22 (LISTEN)
sshd        191            root    4u  IPv6  7340120      0t0  TCP *:22 (LISTEN)
master      295            root   13u  IPv4  7339374      0t0  TCP 127.0.0.1:25 (LISTEN)
master      295            root   14u  IPv6  7339375      0t0  TCP [::1]:25 (LISTEN)
root@ddns:~/PyDDNS# docker-compose up
WARNING: The MAX_DOMAINS_USER variable is not set. Defaulting to a blank string.
Starting pyddns_ddns_1     ... done
Starting pyddns_postgres_1 ... done
Starting pyddns_python_1   ... done
Starting pyddns_nginx_1    ...

ERROR: for pyddns_nginx_1  a bytes-like object is required, not 'str'

ERROR: for nginx  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/1afa5a3f10e16e32420b3eeb11a90dd45cc5a7fac17c2e1a368043103a1661b5/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint pyddns_nginx_1 (d02d3935119793e224e41dba9fe9243cada1c31b2ef2d5cabc982f27c32be1ce): Bind for 0.0.0.0:80 failed: port is already allocated'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 567, in execute_convergence_plan
    return self._execute_convergence_start(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 506, in _execute_convergence_start
    _, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 508, in <lambda>
    lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 620, in start_container_if_stopped
    return self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by olimpo88** [comment]
I sent an update, verify that your ports **HTTPS_PORT** and **HTTP_PORT** in the **.env** file are not the same.

**Comment by kgnfth** [comment]
> I sent an update, verify that your ports **HTTPS_PORT** and **HTTP_PORT** in the **.env** file are not the same.

Thanks that was it.

**Comment by olimpo88** [comment]
> > Envié una actualización, verifique que sus puertos **HTTPS_PORT** y **HTTP_PORT** en el archivo **.env** no sean los mismos.
> 
> Gracias, eso fue todo.



> > I sent an update, verify that your ports **HTTPS_PORT** and **HTTP_PORT** in the **.env** file are not the same.
> 
> Thanks that was it.

@kgnfth  Perfect!

I would appreciate if it could take 5 minutes and validate my knowledge (aptitudes). ballot_box_with_check
https://www.linkedin.com/in/peraltaleandro/
