### ISSUE TITLE
Login form not working, gives error on console

### ISSUE THREAD

**Issue by jacotec** [olimpo88/PyDDNS#25]
I've deployed PyDDNS as per description, but unfortunately I can't login. After entering username and password of my admin user, the "Login" button is not functional.

I'm getting this error on the console:

```
nginx_1     | xx.xxx.xxx.xxx - - [28/May/2021:20:51:30 +0000] "POST /common/dologin/ HTTP/1.1" 302 5 "http://ddns.domain.de/en/common/login/?next=/en/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37" "-"
python_1    | Internal Server Error: /en/common/dologin/
python_1    | Traceback (most recent call last):
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 76, in __getitem__
python_1    |     list_ = super().__getitem__(key)
python_1    | KeyError: 'username'
python_1    | 
python_1    | During handling of the above exception, another exception occurred:
python_1    | 
python_1    | Traceback (most recent call last):
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
python_1    |     response = get_response(request)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
python_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
python_1    |   File "/usr/src/app/common/views.py", line 27, in dologin
python_1    |     username=request.POST['username']
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 78, in __getitem__
python_1    |     raise MultiValueDictKeyError(key)
python_1    | django.utils.datastructures.MultiValueDictKeyError: 'username'
python_1    | [28/May/2021 20:51:30] "GET /en/common/dologin/ HTTP/1.0" 500 64244

```

**Comment by olimpo88** [comment]
Hello, please run the `git pull` command, apparently it was a problem related to the internalization of languages.

**Comment by jacotec** [comment]
Thanks @olimpo88 , that did it!
BTW: Would you like to include a German localization if I'd contribute the translation file?

**Comment by olimpo88** [comment]
Hello @jacotec.
Yes, of course, it is an Opensource project if you send your translation file with a pull request, we will add it.

**Comment by jacotec** [comment]
@olimpo88 Pull request done :-)
